version: "3"
services:
  postgres:
    image: postgres
    network_mode: "host"
    environment:
      POSTGRES_USER: "admin"
      POSTGRES_PASSWORD: "123"
      POSTGRES_DB: algvisual
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
