version: "3"
services:
  algvisual-db:
    image: postgres:15.3-alpine
    environment:
      POSTGRES_USER: "admin"
      POSTGRES_PASSWORD: "123"
      POSTGRES_DB: algvisual
    ports:
      - "5432:5432"
