version: "3"
services:
  app:
    build:
      dockerfile: Dockerfile
      context: .
    volumes:
      - .:/app
    ports:
      - 8000:8000
    environment:
      PG_DATABASE_USER: "admin"
      PG_DATABASE_NAME: "algvisual"
      PG_DATABASE_PASSWORD: "123"
      PG_DATABASE_HOST: "postgres"
      PG_DATABASE_PORT: "5432"
      PHOTOSHOP_FILES_PATH: "/app/dist/photoshop"
      PORT: 8000
      DIST_FOLDER_PATH: "/app/dist"
    links:
      - postgres

  postgres:
    image: postgres
    environment:
      POSTGRES_USER: "admin"
      POSTGRES_PASSWORD: "123"
      POSTGRES_DB: algvisual
    ports:
      - "5432:5432"

