-- Create enum type "component_type"
CREATE TYPE "component_type" AS ENUM ('background', 'logotipo_marca', 'logotipo_produto', 'packshot', 'celebridade', 'modelo', 'ilustracao', 'oferta', 'texto_legal', 'grafismo', 'texto_cta');
-- Create "advertisers" table
CREATE TABLE "advertisers" ("id" bigserial NOT NULL, "name" text NOT NULL, "created_at" timestamp NULL DEFAULT CURRENT_TIMESTAMP, "updated_at" timestamp NULL, "deleted_at" timestamp NULL, PRIMARY KEY ("id"));
-- Create "images" table
CREATE TABLE "images" ("id" bigserial NOT NULL, "url" text NOT NULL, "photoshop_id" integer NULL, "template_id" integer NULL, "created_at" timestamp NULL DEFAULT CURRENT_TIMESTAMP, PRIMARY KEY ("id"));
-- Create enum type "template_type"
CREATE TYPE "template_type" AS ENUM ('slots', 'distortion');
-- Create "clients" table
CREATE TABLE "clients" ("id" bigserial NOT NULL, "name" text NOT NULL, "created_at" timestamp NULL DEFAULT CURRENT_TIMESTAMP, "updated_at" timestamp NULL, "deleted_at" timestamp NULL, PRIMARY KEY ("id"));
-- Create "projects" table
CREATE TABLE "projects" ("id" bigserial NOT NULL, "client_id" integer NULL, "advertiser_id" integer NULL, "briefing" text NULL, "use_ai" boolean NULL DEFAULT false, "name" text NOT NULL, "created_at" timestamp NULL DEFAULT CURRENT_TIMESTAMP, "updated_at" timestamp NULL, "deleted_at" timestamp NULL, PRIMARY KEY ("id"), CONSTRAINT "projects_advertiser_id_fkey" FOREIGN KEY ("advertiser_id") REFERENCES "advertisers" ("id") ON UPDATE CASCADE ON DELETE NO ACTION, CONSTRAINT "projects_client_id_fkey" FOREIGN KEY ("client_id") REFERENCES "clients" ("id") ON UPDATE CASCADE ON DELETE NO ACTION);
-- Create "design" table
CREATE TABLE "design" ("id" serial NOT NULL, "name" text NOT NULL, "image_url" text NULL, "layout_id" integer NULL, "project_id" integer NULL, "image_extension" text NULL, "file_url" text NULL, "file_extension" text NULL, "width" integer NULL, "height" integer NULL, "is_proccessed" boolean NULL DEFAULT false, "created_at" timestamp NULL DEFAULT CURRENT_TIMESTAMP, "updated_at" timestamp NULL, PRIMARY KEY ("id"), CONSTRAINT "design_project_id_fkey" FOREIGN KEY ("project_id") REFERENCES "projects" ("id") ON UPDATE CASCADE ON DELETE NO ACTION);
-- Create "layout" table
CREATE TABLE "layout" ("id" bigserial NOT NULL, "design_id" integer NULL, "is_original" boolean NULL DEFAULT false, "image_url" text NULL, "width" integer NULL, "height" integer NULL, "data" text NULL, "stages" text[] NULL, "created_at" timestamp NULL DEFAULT CURRENT_TIMESTAMP, "updated_at" timestamp NULL, "deleted_at" timestamp NULL, PRIMARY KEY ("id"), CONSTRAINT "fk_layout_design_id" FOREIGN KEY ("design_id") REFERENCES "design" ("id") ON UPDATE CASCADE ON DELETE CASCADE);
-- Create "layout_components" table
CREATE TABLE "layout_components" ("id" serial NOT NULL, "layout_id" integer NOT NULL, "design_id" integer NOT NULL, "width" integer NULL, "height" integer NULL, "is_original" boolean NULL, "color" text NULL, "type" "component_type" NULL, "xi" integer NULL, "xii" integer NULL, "yi" integer NULL, "yii" integer NULL, "bbox_xi" integer NULL, "bbox_xii" integer NULL, "bbox_yi" integer NULL, "bbox_yii" integer NULL, "priority" integer NULL, "inner_xi" integer NULL, "inner_xii" integer NULL, "inner_yi" integer NULL, "inner_yii" integer NULL, "created_at" timestamp NULL DEFAULT CURRENT_TIMESTAMP, PRIMARY KEY ("id"), CONSTRAINT "layout_components_design_id_fkey" FOREIGN KEY ("design_id") REFERENCES "design" ("id") ON UPDATE CASCADE ON DELETE CASCADE, CONSTRAINT "layout_components_layout_id_fkey" FOREIGN KEY ("layout_id") REFERENCES "layout" ("id") ON UPDATE CASCADE ON DELETE CASCADE);
-- Create "layout_elements" table
CREATE TABLE "layout_elements" ("id" serial NOT NULL, "design_id" integer NOT NULL, "layout_id" integer NOT NULL, "component_id" integer NULL, "name" text NULL, "layer_id" text NULL, "text" text NULL, "xi" integer NULL, "xii" integer NULL, "yi" integer NULL, "yii" integer NULL, "inner_xi" integer NULL, "inner_xii" integer NULL, "inner_yi" integer NULL, "inner_yii" integer NULL, "width" integer NULL, "height" integer NULL, "is_group" boolean NULL, "group_id" integer NULL, "level" integer NULL, "kind" text NULL, "image_url" text NULL, "image_extension" text NULL, "created_at" timestamp NULL DEFAULT CURRENT_TIMESTAMP, "updated_at" timestamp NULL, PRIMARY KEY ("id"), CONSTRAINT "fk_design_element_component_id" FOREIGN KEY ("component_id") REFERENCES "layout_components" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION, CONSTRAINT "fk_design_element_design_id" FOREIGN KEY ("design_id") REFERENCES "design" ("id") ON UPDATE CASCADE ON DELETE CASCADE, CONSTRAINT "layout_elements_layout_id_fkey" FOREIGN KEY ("layout_id") REFERENCES "layout" ("id") ON UPDATE CASCADE ON DELETE CASCADE);
-- Create "layout_requests" table
CREATE TABLE "layout_requests" ("id" bigserial NOT NULL, "design_id" integer NULL, "layout_id" integer NULL, "created_at" timestamp NULL DEFAULT CURRENT_TIMESTAMP, "log" text NULL, "config" text NULL, "deleted_at" timestamp NULL, PRIMARY KEY ("id"), CONSTRAINT "layout_requests_design_id_fkey" FOREIGN KEY ("design_id") REFERENCES "design" ("id") ON UPDATE CASCADE ON DELETE CASCADE);
-- Create "templates" table
CREATE TABLE "templates" ("id" serial NOT NULL, "name" text NOT NULL, "request_id" text NULL, "project_id" integer NULL, "width" integer NULL, "height" integer NULL, "slots_x" integer NULL, "slots_y" integer NULL, "max_slots_x" integer NULL, "max_slots_y" integer NULL, "created_at" timestamp NULL DEFAULT CURRENT_TIMESTAMP, "updated_at" timestamp NULL, "deleted_at" timestamp NULL, PRIMARY KEY ("id"), CONSTRAINT "templates_project_id_fkey" FOREIGN KEY ("project_id") REFERENCES "projects" ("id") ON UPDATE CASCADE ON DELETE CASCADE);
-- Create "layout_requests_jobs" table
CREATE TABLE "layout_requests_jobs" ("id" bigserial NOT NULL, "layout_id" integer NULL, "design_id" integer NULL, "request_id" integer NULL, "template_id" integer NULL, "status" text NULL, "image_url" text NULL, "started_at" timestamp NULL, "finished_at" timestamp NULL, "error_at" timestamp NULL, "stopped_at" timestamp NULL, "updated_at" timestamp NULL, "created_at" timestamp NULL DEFAULT CURRENT_TIMESTAMP, "config" text NULL, "log" text NULL, PRIMARY KEY ("id"), CONSTRAINT "layout_requests_jobs_design_id_fkey" FOREIGN KEY ("design_id") REFERENCES "design" ("id") ON UPDATE CASCADE ON DELETE CASCADE, CONSTRAINT "layout_requests_jobs_layout_id_fkey" FOREIGN KEY ("layout_id") REFERENCES "layout" ("id") ON UPDATE CASCADE ON DELETE CASCADE, CONSTRAINT "layout_requests_jobs_request_id_fkey" FOREIGN KEY ("request_id") REFERENCES "layout_requests" ("id") ON UPDATE CASCADE ON DELETE CASCADE, CONSTRAINT "layout_requests_jobs_template_id_fkey" FOREIGN KEY ("template_id") REFERENCES "templates" ("id") ON UPDATE CASCADE ON DELETE CASCADE);
-- Create "templates_distortions" table
CREATE TABLE "templates_distortions" ("id" serial NOT NULL, "x" integer NULL, "y" integer NULL, "created_at" timestamp NULL DEFAULT CURRENT_TIMESTAMP, "updated_at" timestamp NULL, "deleted_at" timestamp NULL, "template_id" integer NOT NULL, PRIMARY KEY ("id"), CONSTRAINT "templates_distortions_template_id_fkey" FOREIGN KEY ("template_id") REFERENCES "templates" ("id") ON UPDATE CASCADE ON DELETE CASCADE);
-- Create "templates_slots" table
CREATE TABLE "templates_slots" ("id" serial NOT NULL, "xi" integer NULL, "yi" integer NULL, "width" integer NULL, "height" integer NULL, "created_at" timestamp NULL DEFAULT CURRENT_TIMESTAMP, "updated_at" timestamp NULL, "deleted_at" timestamp NULL, "template_id" integer NOT NULL, PRIMARY KEY ("id"), CONSTRAINT "templates_slots_template_id_fkey" FOREIGN KEY ("template_id") REFERENCES "templates" ("id") ON UPDATE CASCADE ON DELETE CASCADE);
