// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: photoshop.sql

package database

import (
	"context"
)

const getPhotoshop = `-- name: GetPhotoshop :one
SELECT id, name, bio FROM photoshop
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetPhotoshop(ctx context.Context, id int64) (Photoshop, error) {
	row := q.db.QueryRowContext(ctx, getPhotoshop, id)
	var i Photoshop
	err := row.Scan(&i.ID, &i.Name, &i.Bio)
	return i, err
}
