"""start-migrations

Revision ID: 3f49dc87cb3f
Revises: 
Create Date: 2024-04-15 00:59:06.278246

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3f49dc87cb3f'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('photoshop_files',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(length=100), nullable=False),
    sa.Column('filepath', sa.String(length=255), nullable=False),
    sa.Column('width', sa.Integer(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_photoshop_files_id'), 'photoshop_files', ['id'], unique=False)
    op.create_table('templates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('width', sa.Integer(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('generation_request',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=10), nullable=True),
    sa.Column('log', sa.String(length=50), nullable=True),
    sa.Column('photoshop_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['photoshop_id'], ['photoshop_files.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_generation_request_id'), 'generation_request', ['id'], unique=False)
    op.create_table('photoshop_elements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('component_id', sa.String(length=46), nullable=True),
    sa.Column('component_color', sa.String(length=7), nullable=True),
    sa.Column('is_group', sa.Boolean(), nullable=True),
    sa.Column('is_background', sa.Boolean(), nullable=True),
    sa.Column('image', sa.String(length=46), nullable=True),
    sa.Column('xi', sa.Integer(), nullable=True),
    sa.Column('kind', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('yi', sa.Integer(), nullable=True),
    sa.Column('xii', sa.Integer(), nullable=True),
    sa.Column('yii', sa.Integer(), nullable=True),
    sa.Column('level', sa.Integer(), nullable=True),
    sa.Column('group_id', sa.Integer(), nullable=True),
    sa.Column('layer_id', sa.Integer(), nullable=True),
    sa.Column('photoshop_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['photoshop_id'], ['photoshop_files.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_photoshop_elements_id'), 'photoshop_elements', ['id'], unique=False)
    op.create_table('templates_positions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('xi', sa.Integer(), nullable=True),
    sa.Column('yi', sa.Integer(), nullable=True),
    sa.Column('width', sa.Integer(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('template_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['template_id'], ['templates.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('generation_request_image',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(length=50), nullable=True),
    sa.Column('filepath', sa.String(length=100), nullable=True),
    sa.Column('request_id', sa.Integer(), nullable=True),
    sa.Column('photoshop_id', sa.Integer(), nullable=True),
    sa.Column('template_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['photoshop_id'], ['photoshop_files.id'], ),
    sa.ForeignKeyConstraint(['request_id'], ['generation_request.id'], ),
    sa.ForeignKeyConstraint(['template_id'], ['templates.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_generation_request_image_id'), 'generation_request_image', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_generation_request_image_id'), table_name='generation_request_image')
    op.drop_table('generation_request_image')
    op.drop_table('templates_positions')
    op.drop_index(op.f('ix_photoshop_elements_id'), table_name='photoshop_elements')
    op.drop_table('photoshop_elements')
    op.drop_index(op.f('ix_generation_request_id'), table_name='generation_request')
    op.drop_table('generation_request')
    op.drop_table('templates')
    op.drop_index(op.f('ix_photoshop_files_id'), table_name='photoshop_files')
    op.drop_table('photoshop_files')
    # ### end Alembic commands ###
