// Code generated by templ - DO NOT EDIT.

// templ: version: v0.2.680
package files

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import "context"
import "io"
import "bytes"

import (
	"algvisual/internal/shared"
)

func UploadDesignForm() templ.Component {
	return templ.ComponentFunc(func(ctx context.Context, templ_7745c5c3_W io.Writer) (templ_7745c5c3_Err error) {
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templ_7745c5c3_W.(*bytes.Buffer)
		if !templ_7745c5c3_IsBuffer {
			templ_7745c5c3_Buffer = templ.GetBuffer()
			defer templ.ReleaseBuffer(templ_7745c5c3_Buffer)
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<script type=\"module\" src=\"https://cdn.jsdelivr.net/npm/@shoelace-style/shoelace@2.15.1/cdn/components/button/button.js\"></script><div class=\"cluster\"><form id=\"form\" hx-encoding=\"multipart/form-data\" hx-post=\"")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var2 string
		templ_7745c5c3_Var2, templ_7745c5c3_Err = templ.JoinStringErrs(shared.PageUploadDesignFile.String())
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `web/views/files/form.templ`, Line: 10, Col: 98}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var2))
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("\" hx-swap=\"none\"><div class=\"box\"><input form=\"form\" class=\"uk-input\" placeholder=\"Nome\" type=\"text\" name=\"filename\" placeholder=\"\" required></div><div class=\"box\"><div uk-form-custom=\"target: true\"><input type=\"file\" name=\"file\" aria-label=\"Custom controls\" required> <input class=\"uk-input uk-form-width-medium\" type=\"text\" placeholder=\"Selecionar arquivo\" aria-label=\"Custom controls\" disabled></div><button class=\"uk-button uk-button-default\">Salvar</button></div></form></div><script type=\"text/javascript\">\n        htmx.on('#form', 'htmx:xhr:progress', function(evt) {\n          $(\"#upload-progress\").show()\n          htmx.find('#upload-progress').setAttribute('value', evt.detail.loaded/evt.detail.total * 100)\n        });\n        const Toast = Swal.mixin({\n          toast: true,\n          position: 'center',\n          iconColor: 'white',\n          customClass: {\n            popup: 'colored-toast',\n          },\n          showConfirmButton: false,\n          timer: 1500,\n          timerProgressBar: true,\n        })\n        document.body.addEventListener(\"makeToast\", async function(evt){\n          console.log(evt.detail)\n          if(evt.detail.level == \"success\"){\n            await Toast.fire({\n              icon: 'success',\n              title: 'Sucesso',\n            })\n          } else {\n            await Toast.fire({\n              icon: 'error',\n              title: evt.detail.message,\n            })\n          }\n        })\n        </script>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		if !templ_7745c5c3_IsBuffer {
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteTo(templ_7745c5c3_W)
		}
		return templ_7745c5c3_Err
	})
}
