FROM python:3.10 

WORKDIR /home/ec2-user/alg_visual

RUN pip install poetry

# Copy Application
COPY . /home/ec2-user/alg_visual

# RUN poetry install --no-interaction --no-cache

# RUN poetry export --without-hashes --format=requirements.txt > requirements.txt

RUN pip install --no-cache-dir --upgrade -r requirements.txt

# Run Application
EXPOSE 5000

CMD [ "uvicorn", "app.main:app",  "--host", "0.0.0.0", "--port", "8080","--reload"]con
