FROM python:3.10 

WORKDIR /app

RUN pip install poetry

# Copy Application
COPY . /app

# RUN poetry install --no-interaction --no-cache

# RUN poetry export --without-hashes --format=requirements.txt > requirements.txt

RUN pip install --no-cache-dir --upgrade -r requirements.txt

# Run Application
EXPOSE 8080

CMD [ "uvicorn", "app.main:app",  "--host", "0.0.0.0", "--port", "8080","--reload"]
