// Code generated by templ - DO NOT EDIT.

// templ: version: v0.2.680
package steps

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import "context"
import "io"
import "bytes"

func Steps() templ.Component {
	return templ.ComponentFunc(func(ctx context.Context, templ_7745c5c3_W io.Writer) (templ_7745c5c3_Err error) {
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templ_7745c5c3_W.(*bytes.Buffer)
		if !templ_7745c5c3_IsBuffer {
			templ_7745c5c3_Buffer = templ.GetBuffer()
			defer templ.ReleaseBuffer(templ_7745c5c3_Buffer)
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<ol class=\"flex items-center w-full text-sm font-medium text-center text-gray-500 dark:text-gray-400 sm:text-base\"><li class=\"flex md:w-full items-center text-blue-600 dark:text-blue-500 sm:after:content-[&#39;&#39;] after:w-full after:h-1 after:border-b after:border-gray-200 after:border-1 after:hidden sm:after:inline-block after:mx-6 xl:after:mx-10 dark:after:border-gray-700\"><span class=\"flex items-center after:content-[&#39;/&#39;] sm:after:hidden after:mx-2 after:text-gray-200 dark:after:text-gray-500\"><svg class=\"w-3.5 h-3.5 sm:w-4 sm:h-4 me-2.5\" aria-hidden=\"true\" xmlns=\"http://www.w3.org/2000/svg\" fill=\"currentColor\" viewBox=\"0 0 20 20\"><path d=\"M10 .5a9.5 9.5 0 1 0 9.5 9.5A9.51 9.51 0 0 0 10 .5Zm3.707 8.207-4 4a1 1 0 0 1-1.414 0l-2-2a1 1 0 0 1 1.414-1.414L9 10.586l3.293-3.293a1 1 0 0 1 1.414 1.414Z\"></path></svg> Personal <span class=\"hidden sm:inline-flex sm:ms-2\">Info</span></span></li><li class=\"flex md:w-full items-center after:content-[&#39;&#39;] after:w-full after:h-1 after:border-b after:border-gray-200 after:border-1 after:hidden sm:after:inline-block after:mx-6 xl:after:mx-10 dark:after:border-gray-700\"><span class=\"flex items-center after:content-[&#39;/&#39;] sm:after:hidden after:mx-2 after:text-gray-200 dark:after:text-gray-500\"><span class=\"me-2\">2</span> Account <span class=\"hidden sm:inline-flex sm:ms-2\">Info</span></span></li><li class=\"flex items-center\"><span class=\"me-2\">3</span> Confirmation</li></ol>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		if !templ_7745c5c3_IsBuffer {
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteTo(templ_7745c5c3_W)
		}
		return templ_7745c5c3_Err
	})
}
