// Code generated by templ - DO NOT EDIT.

// templ: version: v0.2.680
package topbar

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import "context"
import "io"
import "bytes"

func HomeBar() templ.Component {
	return templ.ComponentFunc(func(ctx context.Context, templ_7745c5c3_W io.Writer) (templ_7745c5c3_Err error) {
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templ_7745c5c3_W.(*bytes.Buffer)
		if !templ_7745c5c3_IsBuffer {
			templ_7745c5c3_Buffer = templ.GetBuffer()
			defer templ.ReleaseBuffer(templ_7745c5c3_Buffer)
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<div class=\"homebar\"><div class=\"cluster homebar\"><div><a href=\"/\" class=\"box homebar__item active\">Designs</a> <a href=\"/templates\" class=\"box homebar__item\">Templates</a></div></div></div><script>\n        document.addEventListener('DOMContentLoaded', () => {\n            const currentPath = window.location.pathname;\n            const links = document.querySelectorAll('.homebar__item');\n            links.forEach(link => {\n                if (link.getAttribute('href') === currentPath) {\n                    link.classList.add('active');\n                } else {\n                    link.classList.remove('active'); \n                }\n            });\n        });\n    </script>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		if !templ_7745c5c3_IsBuffer {
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteTo(templ_7745c5c3_W)
		}
		return templ_7745c5c3_Err
	})
}
